from __future__ import annotations

from datetime import date
from typing import Protocol, runtime_checkable

import polars as pl


@runtime_checkable
class AccountsRepository(Protocol):
    """Protocol for account equity persistence operations."""

    async def init_tables(self) -> None: ...
    async def store_equity(self, name: str, equity: float) -> None: ...
    async def get_latest_equity(self, name: str) -> float | None: ...
    async def get_equity_history(self, name: str) -> pl.DataFrame: ...


@runtime_checkable
class YoloRepository(Protocol):
    """Protocol for YOLO strategy persistence operations."""

    async def init_tables(self) -> None: ...
    async def store_weights(self, weights: pl.DataFrame) -> None: ...
    async def store_volatilities(self, volatilities: pl.DataFrame) -> None: ...
    async def get_weights(self, _date: date) -> pl.DataFrame: ...
    async def get_volatilities(self, _date: date) -> pl.DataFrame: ...
